---
kind: pipeline
name: user-alpine-3.7
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine arm64v8 arm32v6 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.7-arm64v8
    repo: phasecorex/user-alpine
    tags:
      - 3.7-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.7
      - ARCH=arm64v8

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.7-arm32v6
    repo: phasecorex/user-alpine
    tags:
      - 3.7-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.7
      - ARCH=arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.7-amd64
    repo: phasecorex/user-alpine
    tags:
      - 3.7-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.7
      - ARCH=amd64

- name: docker-push-manifest-3.7
  image: plugins/manifest
  environment:
    DRONE_TAG: 3.7
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-3.8
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine arm64v8 arm32v6 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.8-arm64v8
    repo: phasecorex/user-alpine
    tags:
      - 3.8-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.8
      - ARCH=arm64v8

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.8-arm32v6
    repo: phasecorex/user-alpine
    tags:
      - 3.8-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.8
      - ARCH=arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.8-amd64
    repo: phasecorex/user-alpine
    tags:
      - 3.8-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.8
      - ARCH=amd64

- name: docker-push-manifest-3.8
  image: plugins/manifest
  environment:
    DRONE_TAG: 3.8
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-3.9
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine arm64v8 arm32v7 arm32v6 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.9-arm64v8
    repo: phasecorex/user-alpine
    tags:
      - 3.9-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.9
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.9-arm32v7
    repo: phasecorex/user-alpine
    tags:
      - 3.9-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/alpine:3.9
      - ARCH=arm32v7

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.9-arm32v6
    repo: phasecorex/user-alpine
    tags:
      - 3.9-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.9
      - ARCH=arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.9-amd64
    repo: phasecorex/user-alpine
    tags:
      - 3.9-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.9
      - ARCH=amd64

- name: docker-push-manifest-3.9
  image: plugins/manifest
  environment:
    DRONE_TAG: 3.9
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-edge
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine arm64v8 arm32v7 arm32v6 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:edge-arm64v8
    repo: phasecorex/user-alpine
    tags:
      - edge-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:edge
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:edge-arm32v7
    repo: phasecorex/user-alpine
    tags:
      - edge-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/alpine:edge
      - ARCH=arm32v7

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:edge-arm32v6
    repo: phasecorex/user-alpine
    tags:
      - edge-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:edge
      - ARCH=arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:edge-amd64
    repo: phasecorex/user-alpine
    tags:
      - edge-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:edge
      - ARCH=amd64

- name: docker-push-manifest-edge
  image: plugins/manifest
  environment:
    DRONE_TAG: edge
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-3.10
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine arm64v8 arm32v7 arm32v6 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.10-arm64v8
    repo: phasecorex/user-alpine
    tags:
      - 3.10-arm64v8
      - latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.10
      - ARCH=arm64v8

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.10-arm32v7
    repo: phasecorex/user-alpine
    tags:
      - 3.10-arm32v7
      - latest-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/alpine:3.10
      - ARCH=arm32v7

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.10-arm32v6
    repo: phasecorex/user-alpine
    tags:
      - 3.10-arm32v6
      - latest-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.10
      - ARCH=arm32v6

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    create_repository: true
    cache_from: phasecorex/user-alpine:3.10-amd64
    repo: phasecorex/user-alpine
    tags:
      - 3.10-amd64
      - latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.10
      - ARCH=amd64

- name: docker-push-manifest-3.10
  image: plugins/manifest
  environment:
    DRONE_TAG: 3.10
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-latest
  image: plugins/manifest
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: notify
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure
clone:
  disable: true

steps:
- name: send-notification
  image: appleboy/drone-discord
  allow_failure: true
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      {{#success build.status}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch succeeded!
      {{else}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch failed. Fix me please. {{build.link}}
      {{/success}}

depends_on:
  - user-alpine-3.7
  - user-alpine-3.8
  - user-alpine-3.9
  - user-alpine-edge
  - user-alpine-3.10

