---
kind: pipeline
name: user-alpine-3.6
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine amd64 arm32v6 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.6-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.6
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.6-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.6
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.6-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.6
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 3.6
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-3.7
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine amd64 arm32v6 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.7-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.7
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.7-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.7
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.7-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.7
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 3.7
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-3.8
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine amd64 arm32v6 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.8-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.8
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.8-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.8
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.8-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.8
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 3.8
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-3.9
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine amd64 arm32v6 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.9-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:3.9
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.9-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:3.9
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: 3.9-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:3.9
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 3.9
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-edge
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine amd64 arm32v6 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: edge-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:edge
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: edge-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:edge
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: edge-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:edge
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: edge
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-alpine-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-alpine amd64 arm32v6 arm64v8
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/alpine:latest
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: latest-arm32v6
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/alpine:latest
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-alpine
    tags: latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/alpine:latest
    volumes:
      - name: docker
        path: /var/lib/docker

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

